import { chromium, type BrowserContext, type Page } from 'playwright';
import path from 'node:path';
import os from 'node:os';

const CLOAKBROWSER_PATH = path.join(os.homedir(), '.cloakbrowser/chromium-145.0.7632.159.7/chrome');
const PROFILE_BASE = path.join(os.homedir(), '.cloakbrowser-profiles');

const STEALTH_ARGS = [
    '--no-sandbox',
    '--disable-blink-features=AutomationControlled',
    '--fingerprint=52495',
    '--fingerprint-platform=windows',
    '--fingerprint-gpu-vendor=Google Inc. (NVIDIA)',
    '--fingerprint-gpu-renderer=ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002484) Direct3D11 vs_5_0 ps_5_0, D3D11)',
    '--ignore-gpu-blocklist',
    '--window-size=1920,1080',
];

const IGNORE_DEFAULT_ARGS = ['--enable-automation', '--enable-unsafe-swiftshader'];

export interface BrowserFetchResult {
    data: unknown;
    durationMs: number;
}

/**
 * Owns a persistent Playwright page on a target domain.
 *
 * comix.to's chapters API requires a per-manga `_` signature generated by
 * obfuscated client JS. The signature is opaque to the URL params (limit, page,
 * order all work freely) but tied to the manga ID.
 *
 * Strategy:
 *   1. Navigate to the manga's page → capture the `_` sig from the chapters request
 *   2. Replay with our own params (limit=100) via direct fetch — sig is reusable
 *   3. Paginate with the same sig — all pages for that manga share one sig
 *
 * Ownership: Server creates → App borrows → ProxyRoute borrows for fallback.
 */
export class BrowserSession {
    private context: BrowserContext | null = null;
    private page: Page | null = null;
    private _ready = false;
    private initPromise: Promise<void> | null = null;
    private readonly profileDir: string;

    constructor(
        private readonly domain: string,
        private readonly startUrl: string,
    ) {
        this.profileDir = path.join(PROFILE_BASE, `${domain}-session`);
    }

    get ready(): boolean {
        return this._ready;
    }

    async init(): Promise<void> {
        if (this.initPromise) return this.initPromise;
        this.initPromise = this.doInit();
        return this.initPromise;
    }

    private async doInit(): Promise<void> {
        const start = Date.now();
        console.log(`[browserSession] init ${this.domain}`);

        this.context = await chromium.launchPersistentContext(this.profileDir, {
            executablePath: CLOAKBROWSER_PATH,
            args: STEALTH_ARGS,
            ignoreDefaultArgs: IGNORE_DEFAULT_ARGS,
            headless: false,
            viewport: { width: 1920, height: 1080 },
        });

        this.page = this.context.pages()[0] || await this.context.newPage();
        await this.page.goto(this.startUrl, { waitUntil: 'networkidle', timeout: 30_000 });

        console.log(`[browserSession] ready ${this.domain} ${Date.now() - start}ms`);
        this._ready = true;
    }

    /**
     * Make a signed API request for a manga's chapters.
     *
     * Navigates to the manga page to capture the per-manga `_` signature,
     * then replays it with our own params (limit=100) via direct fetch.
     * All pages for that manga reuse the same signature.
     *
     * Returns a synthetic response merging all pages into one.
     */
    async signedFetch(fullUrl: string): Promise<BrowserFetchResult> {
        if (!this._ready || !this.page) {
            throw new Error('BrowserSession not ready');
        }

        const parsed = new URL(fullUrl);
        const pathStr = parsed.pathname + parsed.search;

        const match = parsed.pathname.match(/\/manga\/([^/]+)\/chapters/);
        if (!match) {
            throw new Error(`Cannot extract mangaId from ${parsed.pathname}`);
        }
        const mangaId = match[1];
        const start = Date.now();

        try {
            const data = await this.fetchAllChapters(mangaId);
            const durationMs = Date.now() - start;
            console.log(`[browserSession] fetch ${pathStr} ${durationMs}ms`);
            return { data, durationMs };
        } catch (e) {
            const durationMs = Date.now() - start;
            const msg = (e as Error)?.message ?? String(e);
            console.log(`[browserSession] fetch-error ${pathStr} ${durationMs}ms ${msg}`);
            throw e;
        }
    }

    /**
     * Capture the per-manga `_` signature by navigating to the manga page,
     * then fetch all chapter pages using that signature with limit=100.
     */
    private async fetchAllChapters(mangaId: string): Promise<unknown> {
        const page = this.page!;

        // Step 1: navigate → capture the `_` sig from the chapters request
        const sig = await this.captureSignature(mangaId);
        console.log(`[browserSession] chapters ${mangaId} sig=${sig.slice(0, 20)}...`);

        // Step 2: fetch page 1 with our own params using the captured sig
        const page1 = await this.fetchChapterPage(mangaId, sig, 1);
        const pagination = page1?.result?.pagination;
        const lastPage = pagination?.last_page ?? 1;
        const page1Items = page1?.result?.items ?? [];

        if (lastPage <= 1) {
            console.log(`[browserSession] chapters ${mangaId} page=1/1 items=${page1Items.length} total=${pagination?.total ?? page1Items.length}`);
            return page1;
        }

        console.log(`[browserSession] chapters ${mangaId} page=1/${lastPage} items=${page1Items.length} total=${pagination?.total ?? '?'} — fetching remaining`);

        // Step 3: fetch remaining pages with the same sig
        const allItems = [...page1Items];
        let failed = 0;

        for (let p = 2; p <= lastPage; p++) {
            try {
                const pageData = await this.fetchChapterPage(mangaId, sig, p);
                const items = pageData?.result?.items ?? [];
                if (items.length > 0) {
                    allItems.push(...items);
                    console.log(`[browserSession] chapters ${mangaId} page=${p}/${lastPage} items=${items.length}`);
                } else {
                    failed++;
                    console.log(`[browserSession] chapters ${mangaId} page=${p}/${lastPage} items=0`);
                }
            } catch (e) {
                failed++;
                console.log(`[browserSession] chapters ${mangaId} page=${p}/${lastPage} error: ${(e as Error).message}`);
            }
        }

        console.log(`[browserSession] chapters ${mangaId} done pages=${lastPage} fetched=${allItems.length} failed=${failed}`);

        return {
            status: 200,
            result: {
                items: allItems,
                pagination: {
                    ...pagination,
                    current_page: 1,
                    last_page: 1,
                    total: allItems.length,
                    count: allItems.length,
                },
            },
        };
    }

    /**
     * Navigate to the manga page and capture the `_` signature from the
     * chapters API request that the page's JS makes automatically.
     */
    private captureSignature(mangaId: string): Promise<string> {
        const page = this.page!;

        return new Promise<string>((resolve, reject) => {
            let settled = false;

            const timeout = setTimeout(() => {
                if (settled) return;
                settled = true;
                page.off('request', handler);
                reject(new Error('Timed out waiting for signed chapters request'));
            }, 15_000);

            const handler = (req: import('playwright').Request) => {
                if (settled) return;
                const url = req.url();
                if (!url.includes(`/manga/${mangaId}/chapters`) || !url.includes('_=')) return;

                settled = true;
                clearTimeout(timeout);
                page.off('request', handler);

                const sig = new URL(url).searchParams.get('_');
                if (sig) {
                    resolve(sig);
                } else {
                    reject(new Error('Signed request found but _ param missing'));
                }
            };

            page.on('request', handler);
            page.goto(`https://${this.domain}/title/${mangaId}`, {
                waitUntil: 'commit',
                timeout: 15_000,
            }).catch(e => {
                if (!settled) {
                    settled = true;
                    clearTimeout(timeout);
                    page.off('request', handler);
                    reject(e);
                }
            });
        });
    }

    /**
     * Fetch a single page of chapters using the captured `_` signature.
     * Direct fetch from the browser page context — inherits cookies.
     */
    private fetchChapterPage(mangaId: string, sig: string, pageNum: number): Promise<any> {
        return this.page!.evaluate(
            async ({ mangaId, sig, pageNum }) => {
                const url = `/api/v2/manga/${mangaId}/chapters?limit=100&page=${pageNum}&order%5Bnumber%5D=desc&time=1&_=${sig}`;
                const res = await fetch(url);
                return res.json();
            },
            { mangaId, sig, pageNum },
        );
    }

    async destroy(): Promise<void> {
        this._ready = false;
        if (this.context) {
            await this.context.close().catch(() => {});
            this.context = null;
            this.page = null;
            this.initPromise = null;
            console.log(`[browserSession] destroyed ${this.domain}`);
        }
    }
}
