import { chromium, type BrowserContext, type Page } from 'playwright';
import path from 'node:path';
import os from 'node:os';

const CLOAKBROWSER_PATH = path.join(os.homedir(), '.cloakbrowser/chromium-145.0.7632.159.7/chrome');
const PROFILE_BASE = path.join(os.homedir(), '.cloakbrowser-profiles');

const STEALTH_ARGS = [
    '--no-sandbox',
    '--disable-blink-features=AutomationControlled',
    '--fingerprint=52495',
    '--fingerprint-platform=windows',
    '--fingerprint-gpu-vendor=Google Inc. (NVIDIA)',
    '--fingerprint-gpu-renderer=ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002484) Direct3D11 vs_5_0 ps_5_0, D3D11)',
    '--ignore-gpu-blocklist',
    '--window-size=1920,1080',
];

const IGNORE_DEFAULT_ARGS = ['--enable-automation', '--enable-unsafe-swiftshader'];

const SIGNED_PATTERN = /\/manga\/([^/]+)\/chapters/;

export interface BrowserFetchResult {
    data: unknown;
    durationMs: number;
}

/**
 * Owns a persistent Playwright page on a target domain.
 *
 * comix.to's chapters API requires a per-manga `_` signature generated by
 * obfuscated client JS. The signature is opaque to URL params (limit, page,
 * order all work freely) but tied to the manga ID.
 *
 * Strategy:
 *   1. Navigate to the manga's page → capture the `_` sig from the chapters request
 *   2. Cache sig in memory — stable within a browser session
 *   3. Replay with our own params (limit=100) via direct fetch
 *   4. Paginate in parallel with the same sig
 *
 * Ownership: Server creates → App borrows → ProxyRoute borrows.
 */
export class BrowserSession {
    private context: BrowserContext | null = null;
    private page: Page | null = null;
    private _ready = false;
    private initPromise: Promise<void> | null = null;
    private readonly profileDir: string;

    /** Per-manga signature cache. Lives as long as the browser session. */
    private readonly sigCache = new Map<string, string>();

    constructor(
        private readonly domain: string,
        private readonly startUrl: string,
    ) {
        this.profileDir = path.join(PROFILE_BASE, `${domain}-session`);
    }

    get ready(): boolean {
        return this._ready;
    }

    /** Does this URL need signed browser fetch? Proxy calls this to skip proxyFetch. */
    needsSigning(url: string): boolean {
        return SIGNED_PATTERN.test(url);
    }

    async init(): Promise<void> {
        if (this.initPromise) return this.initPromise;
        this.initPromise = this.doInit();
        return this.initPromise;
    }

    private async doInit(): Promise<void> {
        const start = Date.now();
        console.log(`[browserSession] init ${this.domain}`);

        this.context = await chromium.launchPersistentContext(this.profileDir, {
            executablePath: CLOAKBROWSER_PATH,
            args: STEALTH_ARGS,
            ignoreDefaultArgs: IGNORE_DEFAULT_ARGS,
            headless: false,
            viewport: { width: 1920, height: 1080 },
        });

        this.page = this.context.pages()[0] || await this.context.newPage();
        await this.page.goto(this.startUrl, { waitUntil: 'networkidle', timeout: 30_000 });

        console.log(`[browserSession] ready ${this.domain} ${Date.now() - start}ms`);
        this._ready = true;
    }

    /**
     * Fetch all chapters for a manga, returning a merged response.
     * Uses cached signature if available, otherwise navigates to capture one.
     */
    async signedFetch(fullUrl: string): Promise<BrowserFetchResult> {
        if (!this._ready || !this.page) {
            throw new Error('BrowserSession not ready');
        }

        const match = fullUrl.match(SIGNED_PATTERN);
        if (!match) {
            throw new Error(`Cannot extract mangaId from ${fullUrl}`);
        }
        const mangaId = match[1];
        const start = Date.now();

        try {
            const data = await this.fetchAllChapters(mangaId);
            const durationMs = Date.now() - start;
            return { data, durationMs };
        } catch (e) {
            const durationMs = Date.now() - start;
            const msg = (e as Error)?.message ?? String(e);
            console.log(`[browserSession] fetch-error ${mangaId} ${durationMs}ms ${msg}`);
            throw e;
        }
    }

    /**
     * Prewarm signatures for a batch of manga IDs.
     * Navigates to each manga page to capture its signature.
     * Skips manga that are already cached.
     */
    async prewarmSigs(mangaIds: string[]): Promise<void> {
        const uncached = mangaIds.filter(id => !this.sigCache.has(id));
        if (uncached.length === 0) return;

        console.log(`[browserSession] prewarm ${uncached.length} sigs (${this.sigCache.size} cached)`);
        let captured = 0;

        for (const mangaId of uncached) {
            try {
                const t0 = Date.now();
                const sig = await this.captureSignature(mangaId);
                this.sigCache.set(mangaId, sig);
                captured++;
                console.log(`[browserSession] prewarm ${mangaId} sig=${sig.slice(0, 16)}… ${Date.now() - t0}ms`);
            } catch (e) {
                console.log(`[browserSession] prewarm ${mangaId} failed: ${(e as Error).message}`);
            }
        }

        console.log(`[browserSession] prewarm done captured=${captured}/${uncached.length} cache=${this.sigCache.size}`);
    }

    private async fetchAllChapters(mangaId: string): Promise<unknown> {
        // Step 1: get signature (cache hit or navigate)
        const t0 = Date.now();
        let sig = this.sigCache.get(mangaId);
        let sigSource: 'cache' | 'nav';

        if (sig) {
            sigSource = 'cache';
        } else {
            sig = await this.captureSignature(mangaId);
            this.sigCache.set(mangaId, sig);
            sigSource = 'nav';
        }
        const sigMs = Date.now() - t0;

        // Step 2: fetch page 1
        const t1 = Date.now();
        const page1 = await this.fetchChapterPage(mangaId, sig, 1);
        const p1Ms = Date.now() - t1;
        const pagination = page1?.result?.pagination;
        const lastPage = pagination?.last_page ?? 1;
        const page1Items = page1?.result?.items ?? [];

        if (lastPage <= 1) {
            console.log(`[browserSession] chapters ${mangaId} sig=${sigSource}:${sigMs}ms p1=${p1Ms}ms items=${page1Items.length} total=${pagination?.total ?? page1Items.length}`);
            return page1;
        }

        console.log(`[browserSession] chapters ${mangaId} sig=${sigSource}:${sigMs}ms p1=${p1Ms}ms page=1/${lastPage} items=${page1Items.length} total=${pagination?.total ?? '?'} — fetching remaining`);

        // Step 3: fetch remaining pages in parallel
        const t2 = Date.now();
        const pageNums = Array.from({ length: lastPage - 1 }, (_, i) => i + 2);
        const results = await Promise.allSettled(
            pageNums.map(p => this.fetchChapterPage(mangaId, sig!, p)),
        );

        const allItems = [...page1Items];
        let failed = 0;
        for (let i = 0; i < results.length; i++) {
            const r = results[i];
            const p = pageNums[i];
            if (r.status === 'fulfilled') {
                const items = r.value?.result?.items ?? [];
                if (items.length > 0) {
                    allItems.push(...items);
                } else {
                    failed++;
                    console.log(`[browserSession] chapters ${mangaId} page=${p}/${lastPage} items=0`);
                }
            } else {
                failed++;
                console.log(`[browserSession] chapters ${mangaId} page=${p}/${lastPage} error: ${r.reason?.message}`);
            }
        }
        const pNMs = Date.now() - t2;

        console.log(`[browserSession] chapters ${mangaId} done sig=${sigSource}:${sigMs}ms p1=${p1Ms}ms p2-${lastPage}=${pNMs}ms fetched=${allItems.length} failed=${failed}`);

        return {
            status: 200,
            result: {
                items: allItems,
                pagination: {
                    ...pagination,
                    current_page: 1,
                    last_page: 1,
                    total: allItems.length,
                    count: allItems.length,
                },
            },
        };
    }

    /**
     * Navigate to the manga page and capture the `_` signature from the
     * chapters API request that the page's JS makes automatically.
     */
    private captureSignature(mangaId: string): Promise<string> {
        const page = this.page!;

        return new Promise<string>((resolve, reject) => {
            let settled = false;

            const timeout = setTimeout(() => {
                if (settled) return;
                settled = true;
                page.off('request', handler);
                reject(new Error('Timed out waiting for signed chapters request'));
            }, 15_000);

            const handler = (req: import('playwright').Request) => {
                if (settled) return;
                const url = req.url();
                if (!url.includes(`/manga/${mangaId}/chapters`) || !url.includes('_=')) return;

                settled = true;
                clearTimeout(timeout);
                page.off('request', handler);

                const sig = new URL(url).searchParams.get('_');
                if (sig) {
                    resolve(sig);
                } else {
                    reject(new Error('Signed request found but _ param missing'));
                }
            };

            page.on('request', handler);
            page.goto(`https://${this.domain}/title/${mangaId}`, {
                waitUntil: 'commit',
                timeout: 15_000,
            }).catch(e => {
                if (!settled) {
                    settled = true;
                    clearTimeout(timeout);
                    page.off('request', handler);
                    reject(e);
                }
            });
        });
    }

    /**
     * Fetch a single page of chapters using the captured `_` signature.
     * Direct fetch from the browser page context — inherits cookies.
     */
    private fetchChapterPage(mangaId: string, sig: string, pageNum: number): Promise<any> {
        return this.page!.evaluate(
            async ({ mangaId, sig, pageNum }) => {
                const url = `/api/v2/manga/${mangaId}/chapters?limit=100&page=${pageNum}&order%5Bnumber%5D=desc&time=1&_=${sig}`;
                const res = await fetch(url);
                return res.json();
            },
            { mangaId, sig, pageNum },
        );
    }

    async destroy(): Promise<void> {
        this._ready = false;
        if (this.context) {
            await this.context.close().catch(() => {});
            this.context = null;
            this.page = null;
            this.initPromise = null;
            console.log(`[browserSession] destroyed ${this.domain} sigCache=${this.sigCache.size}`);
        }
    }
}
