export const SWIPE_THRESHOLD = 0.15;
export const DEADZONE_RATIO = 0.013;
export const EDGE_ZONE_RATIO = 0.077;

export const RESUME_RECOVERY_MS = 5_000;
export const DEEP_SLEEP_MS = 10 * 60 * 1000;

export const SEARCH_DEBOUNCE_MS = 500;

export const VISIBLE_MANGA_DEBOUNCE_MS = 1_000;

export const VISIBLE_PAGE_RATIO = 1 / 3;
export const SCROLL_DEBOUNCE_MS = 500;
export const HISTORY_SYNC_MS = 500;

export const SENTINEL_ROOT_MARGIN = '500% 0px';
export const READER_WINDOW_RADIUS_VIEWPORTS = 10;
export const READER_DOM_KEEP_RADIUS_VIEWPORTS = 12;
export const READER_IMAGE_KEEP_RADIUS_VIEWPORTS = 14;
export const READER_IMAGE_ROOT_MARGIN = '1000% 0px';
export const READER_CHAPTER_SEPARATOR_HEIGHT = 52;
export const READER_FALLBACK_PAGE_ASPECT_RATIO = 1.5;

export const LOADING_TIMEOUT_MS = 15_000;
